Update code.sh to use new VSCode shell profiles for integrated terminal.
owtaylor/toolbox-vscode pull request #24
Opened 2022-03-07 18:07 UTC by lbssousa

This PR replaces deprecated VSCode setting `terminal.integrated.shell.linux` in favour of new `terminal.integrated.profiles.linux` one.

2022-03-07 18:40 UTC, owtaylor commented
Failing test was my fault - didn't update the tests for a previous commit - when you rebase, will be fixed.

2022-03-07 18:43 UTC, owtaylor requested changes
Looks great - I've been using a similar config locally for a couple of months - thanks!

Can you change the profile name from "capsh" to "toolbox" so it appears in the UI as "toolbox (Default)") rather than "capsh (Default)" - while, strictly speaking the "bash" profile will also run in the toolbox, the "toolbox" name gives the user a clue "yes, use this one" rather than "what's a capsh".
 
Also, this doesn't fix #11 - which I consider to actually about the "-c" issue - so can you edit that out of your comment?

2022-03-09 14:47 UTC, owtaylor commented
Thanks for the update! Can you also fix tests/test-basic.sh so that ./run-tests.sh passes. Thanks!

(Because it's hard to actually test out the functionality, a lot of the test suite is just checking that the commands run and the config files created are as expected - so it needs quite a bit of adjustment.)

2022-03-09 14:48 UTC, owtaylor approved these changes

2022-03-09 15:36 UTC, lbssousa commented
@owtaylor I've just updated the tests. It should be OK now.

2022-03-09 16:19 UTC, owtaylor commented
Great. Would you mind squashing into a single commit? (`git rebase -i`) - my personal preference is to optimize for readability of the history and also (where possible) to avoid having places in the history where tests are broken. Thanks!

2022-03-09 16:24 UTC, lbssousa commented
@owtaylor Commits squashed

2022-03-09 16:34 UTC, merged